services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=zgdump@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "4080:8080"
    volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    image: ghcr.io/vklachkov/space-fest-ui-frontend:latest
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_frontend.rule=Host(`spacechamp-org.ru`)"
      - "traefik.http.routers.spacefest_frontend.entrypoints=websecure"
      - "traefik.http.routers.spacefest_frontend.tls=true"
      - "traefik.http.routers.spacefest_frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.spacefest_frontend.loadBalancer.server.port=80"

  backend:
    image: ghcr.io/vklachkov/space-fest-ui-backend:latest
    volumes:
      - "backend-data:/var/lib/backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_backend.rule=Host(`spacechamp-org.ru`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.spacefest_backend.entrypoints=websecure"
      - "traefik.http.routers.spacefest_backend.tls=true"
      - "traefik.http.routers.spacefest_backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.spacefest_backend.loadBalancer.server.port=80"

volumes:
  backend-data:
