services:
  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "4080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_frontend.rule=Host(`spacechamp-org.ru`)"
      - "traefik.http.services.spacefest_frontend.loadBalancer.server.port=80"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - "backend-data:/var/lib/backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_backend.rule=Host(`api.spacechamp-org.ru`)"
      - "traefik.http.services.spacefest_backend.loadBalancer.server.port=80"

volumes:
  backend-data:
