services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.spaceresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.spaceresolver.acme.email=zgdump@gmail.com"
      - "--certificatesresolvers.spaceresolver.acme.storage=/etc/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "4080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  # TODO: убрать хардкод на образ 
  frontend:
    image: ghcr.io/vklachkov/space-fest-ui-frontend:latest
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_frontend.rule=Host(`spacechamp-org.ru`)"
      - "traefik.http.routers.spacefest_frontend.entrypoints=websecure"
      - "traefik.http.routers.spacefest_frontend.tls.certresolver=spaceresolver"
      - "traefik.http.services.spacefest_frontend.loadBalancer.server.port=80"

  backend:
    image: ghcr.io/vklachkov/space-fest-ui-backend:latest
    volumes:
      - "backend-data:/var/lib/backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spacefest_backend.rule=Host(`spacechamp-org.ru`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.spacefest_backend.entrypoints=websecure"
      - "traefik.http.routers.spacefest_backend.tls.certresolver=spaceresolver"
      - "traefik.http.services.spacefest_backend.loadBalancer.server.port=80"

volumes:
  backend-data:
