name: Front Deploy

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]
    types: [closed]
    paths:
      - "frontend/**"
      - ".github/workflows/**"

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
    - name: Get image name in lowercase
      id: formatting
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ steps.formatting.outputs.lowercase }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        
  deploy:
    needs: [publish-image]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Stop all containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker stop $(docker ps -a -q)
      - name: Pull latest image version
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{env.IMAGE_TAG}}
      - name: Run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker run -d --network host ${{ env.REGISTRY }}/${{ github.repository }}:${{env.IMAGE_TAG}}